/* USERS */
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const UPDATE_ME = 'UPDATE_ME';
export const UPDATE_ME_SUCCESS = 'UPDATE_ME_SUCCESS';
export const UPDATE_ME_ERROR = 'UPDATE_ME_ERROR';

/* CALLS */
export const CALL_MODAL_STATUS = 'CALL_MODAL_STATUS';
export const SET_CALL = 'SET_CALL';

/* TWILIO */
export const GET_TWILLIO_CONFIG = 'SET_TWILLIO_CONFIG';
export const GET_TWILLIO_CONFIG_SUCCESS = 'SET_TWILLIO_CONFIG_SUCCESS';
export const GET_TWILLIO_CONFIG_FAIL = 'SET_TWILLIO_CONFIG_FAIL';
