name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }} REACT_APP_SOCKET_URL=${{ secrets.REACT_APP_SOCKET_URL }} REACT_APP_SOCKET_PATH=${{ secrets.REACT_APP_SOCKET_PATH }}  REACT_APP_VIOLATION_API=${{ secrets.REACT_APP_VIOLATION_API }} npm run-script build
      env:
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
        REACT_APP_SOCKET_URL: ${{ secrets.REACT_APP_SOCKET_URL }}
        REACT_APP_SOCKET_PATH: ${{ secrets.REACT_APP_SOCKET_PATH }}
        REACT_APP_VIOLATION_API:  ${{ secrets.REACT_APP_VIOLATION_API }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
